AWSTemplateFormatVersion: '2010-09-09'
Description: 'Parent stack for Amazon Connect deployment'

Conditions:
  # us-east-1の場合のみWAFを作成
  IsUsEast1: !Equals [!Ref Region, 'us-east-1']

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Common Configuration"
        Parameters:
          - AwsAccountId
          - Region
      - Label:
          default: "Connect Configuration"
        Parameters:
          - InstanceAlias
          - ConnectInstanceArn
          - CasesDomainId
      - Label:
          default: "Amazon Connect AI agents Configuration"
        Parameters:
          - QiCDomainArn
      - Label:
          default: "3rd Party Application Configuration"
        Parameters:
          - ApplicationName
    ParameterLabels:
      AwsAccountId:
        default: "AWS Account ID"
      Region:
        default: "AWS Region"
      InstanceAlias:
        default: "Connect InstanceAlias"
      ConnectInstanceArn:
        default: "Connect Instance ARN"
      CasesDomainId:
        default: "Connect cases domain ID"
      QiCDomainArn:
        default: "Connect AI agents domain ARN"
      ApplicationName:
        default: "3rd Party Application Name"

Parameters:
  AwsAccountId:
    Type: String
    Description: 'AWS Account ID'
  
  InstanceAlias:
    Type: String
    Description: 'The instance alias for the Amazon Connect instance'
    MaxLength: 64
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Instance alias can only contain lowercase letters, numbers, and hyphens.'
  
  ConnectInstanceArn:
    Type: String
    Description: 'ARN of the Amazon Connect instance'
    Default: 'arn:aws:connect:ap-northeast-1:xxxx:instance/xxxx'
  
  QiCDomainArn:
    Type: String
    Description: 'Connect AI agents domain Arn'
    Default: 'arn:aws:wisdom:ap-northeast-1:xxxx:assistant/xxxx'
  
  CasesDomainId:
    Type: String
    Description: 'ID of the Amazon Connect cases domain'
  
  # Application Parameters
  ApplicationName:
    Type: String
    Description: 'Name of the Connect 3rd Party Application'
    Default: 'MyConnectApp'
  
  Region:
    Type: String
    Description: Target Region to specify Amazon Connect instance, S3 bucket, and LLM for Connect AI agents prompts
    Default: ap-northeast-1
    AllowedValues:
      - ap-northeast-1
      - us-east-1

Resources:
  # 1. ConversationalBot Stack
  ConversationalBotStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://amazonconnect-${InstanceAlias}-app.s3.${AWS::Region}.amazonaws.com/amazon-connect-project/cfn_template/ac-pkg-phase3-lexbot.yaml'
      Parameters:
        ConnectInstanceArn: !Ref ConnectInstanceArn 
        QiCAssistantArn: !Ref QiCDomainArn
        QiCAssistantId: !Select [1, !Split ['assistant/', !Ref QiCDomainArn]]  # AssistantIdを抽出 
        LexBotName: !Sub '${AWS::StackName}-lex-aiagents' 
        LexBotAliasName: !Sub '${AWS::StackName}-demo' 

  # 2. CasesTemplate Stack
  CasesTemplateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ConversationalBotStack
    Properties:
      TemplateURL: !Sub 'https://amazonconnect-${InstanceAlias}-app.s3.${AWS::Region}.amazonaws.com/amazon-connect-project/cfn_template/ac-pkg-phase3-casetemplate-stack.yaml'
      Parameters:
        CasesDomainId: !Ref CasesDomainId
        CasesTemplateName: !Sub '${AWS::StackName}-cases-template'

  # 3. QiC AI Agent Stack
  QiCAIAgentStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CasesTemplateStack
    Properties:
      TemplateURL: !Sub 'https://amazonconnect-${InstanceAlias}-app.s3.${AWS::Region}.amazonaws.com/amazon-connect-project/cfn_template/ac-pkg-phase3-qic-stack.yaml'
      Parameters:
        AssistantId: !Select [1, !Split ['assistant/', !Ref QiCDomainArn]]  # AssistantIdを抽出
        QicPrefix: !Ref 'AWS::StackName'
        ConnectInstanceArn: !Ref ConnectInstanceArn
        Region: !Ref Region

  # 4. Contact Flow Stack
  ContactFlowStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: QiCAIAgentStack
    Properties:
      TemplateURL: !Sub 'https://amazonconnect-${InstanceAlias}-app.s3.${AWS::Region}.amazonaws.com/amazon-connect-project/cfn_template/ac-pkg-phase3-contactflow-stack.yaml'
      Parameters:
        AwsAccountId: !Ref AwsAccountId
        ConnectInstanceArn: !Ref ConnectInstanceArn
        QiCDomainArn: !Ref QiCDomainArn
        CaseTemplateName: !Sub '${AWS::StackName}-cases-template'
        CaseTemplateId: !GetAtt CasesTemplateStack.Outputs.TemplateId
        LexBotName: !GetAtt ConversationalBotStack.Outputs.OrchestrationLexBotName
        LexBotId: !GetAtt ConversationalBotStack.Outputs.OrchestrationLexBotId
        LexBotAliasName: !Sub '${AWS::StackName}-demo' 
        LexBotAliasId: !GetAtt ConversationalBotStack.Outputs.OrchestrationLexBotAliasId
        FlowNamePrefix: !Ref 'AWS::StackName'
        Region: !Ref Region
        SelfServiceOrchestrationAIAgentArn: !GetAtt QiCAIAgentStack.Outputs.SelfServiceOrchestrationAIAgentArn
        SelfServiceOrchestrationAIAgentName: !GetAtt QiCAIAgentStack.Outputs.SelfServiceOrchestrationAIAgentName

  # 5. 3rd Party App Stack  
  ThirdPartyAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ContactFlowStack
    Properties:
      TemplateURL: !Sub 'https://amazonconnect-${InstanceAlias}-app.s3.${AWS::Region}.amazonaws.com/amazon-connect-project/cfn_template/ac-pkg-phase3-app-stack.yaml'
      Parameters:
        BucketNameApp: !Sub 'amazonconnect-${InstanceAlias}-app'
        BucketNameLogs: !Sub 'amazonconnect-${InstanceAlias}-logs'
        ProjectPath: 'amazon-connect-project'
        PublicPath: 'public'
        Region: !Ref Region
        ConnectInstanceArn: !Ref ConnectInstanceArn
        ApplicationName: !Ref ApplicationName
        SecurityProfileName: 'CustomAgent'
        # us-east-1の場合のみWebACLNameとScopeを渡す、それ以外は空文字
        WebACLName: !If [IsUsEast1, !Sub '${AWS::StackName}-myapp-webacl', '']
        Scope: !If [IsUsEast1, 'CLOUDFRONT', '']

Outputs:
  ConversationalBotStack:
    Description: 'ID of the ConversationalBot Stack'
    Value: !Ref ConversationalBotStack
  
  CasesTemplateStack:
    Description: 'ID of the CasesTemplate Stack'
    Value: !Ref CasesTemplateStack
  
  ConnectAIagentsStackId:
    Description: 'ID of the Connect AI agents Stack'
    Value: !Ref QiCAIAgentStack
  
  ContactFlowStackId:
    Description: 'ID of the ConnectFlow Stack'
    Value: !Ref ContactFlowStack
  
  ThirdPartyAppStackId:
    Description: 'ID of the Third Party App Stack'
    Value: !Ref ThirdPartyAppStack
  
  StackName:
    Description: 'Name of this stack'
    Value: !Ref 'AWS::StackName'
  
  Region:
    Description: 'Selected region'
    Value: !Ref Region
  
  WAFEnabled:
    Description: 'Whether WAF is enabled (only in us-east-1)'
    Value: !If [IsUsEast1, 'true', 'false']
